Display addpage
famiconb/calendar pull request #19
Opened 2022-05-24 06:33 UTC by rikuyam

2022-05-24 09:10 UTC, MysteryJump requested changes

2022-05-24 09:10 UTC, MysteryJump commented on renderer/pages/add-page.tsx
> +  const handleBeginChange = (event: any) => {
const handleBeginChange: React.ChangeEventHandler<HTMLSelectElement> = (event) => {

みたいな感じが好きなんですが長いのでany使うのでも問題ないです（HTMLInputElementとかもある）

2022-05-24 09:17 UTC, Nagarei requested changes

2022-05-24 09:17 UTC, Nagarei commented on renderer/pages/add-page.tsx
> +      };
```suggestion
      const date = {
        dayOfWeek: dow,
        period: [],
      };
      for (let i = begin; i <= end; ++i) {
        date.period.push(i);
      }
```

2022-05-30 08:23 UTC, rikuyam commented on renderer/pages/add-page.tsx
> +  const handleBeginChange = (event: any) => {
`const handleBeginChange: React.ChangeEventHandler`とすると、`event.target.value`にて、プロパティ'value'は’ElementTarget & Element' に存在しません。となります。

2022-05-30 08:24 UTC, rikuyam commented on package.json
> +    "node_module": "^0.0.0",
https://github.com/famiconb/calendar/pull/19/commits/cf53a7ada01f1ea9591e10c61020f8fed31ecb8e

2022-05-30 08:24 UTC, rikuyam commented on renderer/pages/add-page.tsx
> +    console.log(dows);
https://github.com/famiconb/calendar/pull/19/commits/cf53a7ada01f1ea9591e10c61020f8fed31ecb8e

2022-05-31 03:23 UTC, MysteryJump commented on renderer/pages/add-page.tsx
> +  const handleBeginChange = (event: any) => {
React.ChangeEventHandler<HTMLSelectElement>ですね、すみません:bow:

2022-05-31 06:38 UTC, MysteryJump approved these changes

2022-05-31 06:43 UTC, Nagarei approved these changes

2022-05-31 07:08 UTC, merged