validate lecture
famiconb/calendar pull request #60
Opened 2022-06-28 06:46 UTC by rikuyam

2022-06-28 07:13 UTC, Nagarei commented on renderer/pages/add-page.tsx
> +                errorMessages.push("開講日時が既存の講義と重複しています。");
もう少し詳しい情報出してあげてもよいかもしれない

2022-06-28 07:19 UTC, rikuyam commented on renderer/pages/add-page.tsx
> +                errorMessages.push("開講日時が既存の講義と重複しています。");
https://github.com/famiconb/calendar/pull/60/commits/e2460d5571acb86f9f3e0f93d3fd5f05dac93c3d

2022-06-28 07:34 UTC, Nagarei commented on renderer/pages/add-page.tsx
> +  const errorMessages: string[] = [];
onSubmit の中で定義するのが良い気がします

2022-06-28 07:39 UTC, Nagarei requested changes

2022-06-28 07:39 UTC, Nagarei commented on renderer/pages/add-page.tsx
> +      for (const period of date.period) {
periodが昇順であることを確認してほしいです

2022-06-28 07:41 UTC, Nagarei commented
edit-page 80行目
memo: memoのままになっているので、memo: []にするのをお願いします

2022-06-28 07:43 UTC, Nagarei commented on renderer/pages/add-page.tsx
> +      errorMessages.push("titleは必要です。");
```suggestion
      errorMessages.push("授業名は必要です。");
```

edit-pageの方もお願いします

2022-06-28 09:07 UTC, rikuyam commented on renderer/pages/add-page.tsx
> +      for (const period of date.period) {
https://github.com/famiconb/calendar/pull/60/commits/d4bb22b04af9cee421449f883f41e7979028cd0d

2022-06-28 09:09 UTC, rikuyam commented on renderer/pages/add-page.tsx
> +      errorMessages.push("titleは必要です。");
[98dce31](https://github.com/famiconb/calendar/pull/60/commits/98dce318dc8d9eaf31fa47e66b8ab066a2531c3b)

2022-07-05 05:28 UTC, Nagarei commented on renderer/pages/add-page.tsx
> +      for (const period of date.period) {
なるほど確かに

2022-07-05 05:34 UTC, Nagarei approved these changes

2022-07-05 05:34 UTC, merged